openapi: 3.0.3
info:
  title: Swagger Maschinenpark
  version: 1.0.0
tags:
  - name: Dobot
    description: Everything about your Dobot
  - name: SPS
    description: SPS
  - name: Monitor
    description: Operations about main
paths:
  /Dobot/Login:
    post:
      tags:
        - Dobot
      summary: Monitor IP Address
      description: Get monitor IP
      operationId: monitorIp
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  
  /Monitor/GetJobs:
    get:
      tags:
        - Monitor
      summary: Gets the jobs of the device
      description: Retrieves the jobs of the device.
      operationId: getMonitorJobs
      parameters:
        - name: Ip
          in: query
          description: Device IP Address
          required: true
          schema:
            type: string
            example: '192.168.1.1'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobsVomGeraet'
            application/xml:
              schema:
                $ref: '#/components/schemas/JobsVomGeraet'
        '400':
          description: error
        '404':
          description: not found
          
  /SPS/Login:
    post:
      tags:
        - SPS
      summary: SPS Login adress
      description: Post SPS Login
      operationId: spsId
      requestBody:
        description: Posts Login with Ip, GuId, and DeviceType
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '200':
          description: Successfully logged in!
        '400':
          description: Invalid input
        '422':
          description: Validation exception
components:
  schemas:
    Login:
      type: object
      properties:
        Ip:
          type: string
          format: string
          example: '192.128.1.1'
        GuId:
          type: string
          example: 'b805b5ce-43fd-4d42-b6c9-db40ce8a95d9'
        DeviceType:
          type: integer
          example: 2
      xml:
        name: login
    JobsVomGeraet:
      type: object
      properties:
        Ip:
          type: string
          format: string
          example: '192.128.1.1'
        GerätId:
          type: string
          example: 'b805b5ce-43fd-4d42-b6c9-db40ce8a95d9'
        JobIds:
          type: string
          description: kommaseparierte Liste
          example: 'b805b5ce-43fd-4d42-b6c9-db40ce8a95d9,a605b5ce-43fd-4d42-b6c9-db40ce8a95d9'
      xml:
        name: Jobs
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  requestBodies:
    Login:
      description: Login
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Login'
        application/xml:
          schema:
            $ref: '#/components/schemas/Login'
 
