openapi: 3.0.3
info:
  title: Swagger Maschinenpark
  version: 1.0.0
tags:
  - name: Device
    description: Everything for the devices
  - name: Monitor
    description: Operations about main
paths:

  /api/device/setMonitorIp:
    post:
      tags: 
        - Device
      summary: gets the ip from the monitor
      parameters:
        - name: ip
          description: monitor ip
          in: query
          required: true
          schema:
            type: string
            example: '192.168.1.1'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        
    
  /api/monitor/login:
    post:
      tags:
        - Monitor
      summary: registration
      description: registration
      operationId: deviceRegistration
      requestBody:
        description: post login
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '422':
          description: Validation exception
          
  /api/log/:
    post:
      tags:
        - Monitor
      summary: status changed
      requestBody:
        description: post status changed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/statusChanged'
              required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '422':
          description: Validation exception
          
  /api/device/notstop:
    delete:
      tags:
        - Device
      summary: stops the jobs
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  
  /api/device/getJobs:
    get:
      tags:
        - Device
      summary: Gets the jobs of the device
      description: Retrieves the jobs of the device.
      operationId: getMonitorJobs
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobsVomGeraet'
            application/xml:
              schema:
                $ref: '#/components/schemas/JobsVomGeraet'
        '400':
          description: error
        '404':
          description: not found

components:
  schemas:
    Login:
      type: object
      properties:
        ip:
          type: string
          format: string
          example: '192.128.1.1'
        id:
          type: string
          example: 'b805b5ce-43fd-4d42-b6c9-db40ce8a95d9'
        type:
          type: string
          example: "dobot"
        name:
          type: string
          description: max. 20 Zeichen
          example: dobot 1
      xml:
        name: login
        
    statusChanged:
      type: object
      properties:
        deviceId:
          type: string
          example: 'b805b5ce-43fd-4d42-b6c9-db40ce8a95d9'
        jobId:
          type: string
          example: 'b805b5ce-43fd-4d42-b6c9-db40ce8a95d9'
        level:
          type: string
          example: "info"
        timestamp:
          type: string
          example: "2024-02-22T09:02:11+0000"
        message:
          type: string
          example: "Sauger ist kaputt"
        status:
          type: string
          example: gestartet
      xml:
        name: statusChanged
    
    JobsVomGeraet:
      type: object
      properties:
        deviceId:
          type: string
          example: 'b805b5ce-43fd-4d42-b6c9-db40ce8a95d9'
        jobs:
          type: json
          example: "'805b5ce-43fd-4d42-b6c9-db40ce8a95d9, Job1', 'a605b5ce-43fd-4d42-b6c9-db40ce8a95d9, Job2'"
      xml:
        name: Jobs
        
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  requestBodies:
    Login:
      description: Login
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Login'
        application/xml:
          schema:
            $ref: '#/components/schemas/Login'
 
